version: "3.8"

services:
  db:
    container_name: postgres_db
    image: postgres
    # automatically restarts the container 
    # when Docker daemon restarts or container is restarted manually
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=uaecodes
    ports:
      - "5432:5432"

  app:
    container_name: uaecodes
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
        - .env
    ports:
      - "80:8000"
    volumes:
      - .:/app
    depends_on:
      - db
 

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      # PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin: